version: '3'

services:
  mongo:
    image: mongo
    container_name: mongo
    #network_mode: 'host'
    #restart: always
    ports:
      - 27017:27017
    environment:
     TZ: 'Asia/Shanghai'
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    #network_mode: "host"
    #restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH_USERNAME: express
      ME_CONFIG_BASICAUTH_PASSWORD: express123
      #ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      #ME_CONFIG_MONGODB_ADMINPASSWORD: admin123 
    depends_on:
      - mongo
  splash:
    image: scrapinghub/splash
    container_name: splash
    ports:
      - 8050:8050
